;SDK_CFG Version 4.2.17.0
[HostConfig]
InBoxPath=Test Pic
SaveImage=1
Sensitivity=0
SynBoxMode=0
SynBoxPort=0
SDKDebug=0
SDKLogLevel=1
LOGClose=0
SDKEnhance=0
log_path=log_tmp
RecoveryTime =10
GetTypeFromPCcfg=0
BufferDepth=1
BATTLOW1=25
BATTLOW2=20
OrderlyIdQueue=0

[Template]
FPType=4343
ShiftRow=0
ShiftCol=0
PicRow=3072
PicCol=3072
PostProcessing=6
tpl_path=raw
dark_count=8
flood_count=8
aed_count=10
AedTplGenerate=0

BinCount=2
Cfg0Bin1Xwin=100
Cfg0Bin2Xwin=100
Cfg0Bin3Xwin=100
Cfg0Bin4Xwin=100
Cfg0Bin6Xwin=100
Cfg1Bin1Xwin=100
Cfg1Bin2Xwin=100
Cfg1Bin3Xwin=100
Cfg1Bin4Xwin=100
Cfg1Bin6Xwin=100
DarkValueL=1000
DarkValueH=20000
FloodValueL=25000
FloodValueH=50000
DarkValueDelt=100
FloodValueDelt=200
FilterCount=10

ShiftRowReverse=0
ShiftColReverse=0
BackValue=0
RawGain=0
LUT=0
Sharp=0
SilkPair=0
LoadAllBinTpl=0

PanelGridEnable=0
Panel0SN=AGAabcd6789
Panel0GridDirection=1
Panel0GridCycle=9

Panel1SN=AGAabcd9999
Panel1GridDirection=1
Panel1GridCycle=9

[DefectPara]
Defect_min=500
Defect_max=65000
Defect_STD_M=6
Defect_STD_Mex=5
Defect_rate_dark=100
Defect_rate_flood=100
Defect_line=10

[IPConfig]
IPAllocate=1
HostIPAddr=
UDPPortStart=30714

[SynBoxTime]
expose_clock=750
turb_clock=1800
ready_clock=1560
xwin_clock=1000

[Bin1Gain]
IFS0=15
REF0=48
IFS1=25
REF1=37
IFS2=35
REF2=30
IFS3=45
REF3=28
IFS4=55
REF4=26
IFS5=63
REF5=25
[Bin2Gain]
IFS0=15
REF0=90
IFS1=25
REF1=60
IFS2=35
REF2=48
IFS3=45
REF3=40
IFS4=55
REF4=37
IFS5=63
REF5=35
[Bin3Gain]
IFS0=15
REF0=130
IFS1=25
REF1=86
IFS2=35
REF2=67
IFS3=45
REF3=55
IFS4=55
REF4=46
IFS5=63
REF5=42
[Bin4Gain]
IFS0=22
REF0=120
IFS1=30
REF1=95
IFS2=38
REF2=76
IFS3=46
REF3=66
IFS4=54
REF4=59
IFS5=63
REF5=50
[Bin6Gain]
IFS0=31
REF0=130
IFS1=38
REF1=110
IFS2=45
REF2=94
IFS3=51
REF3=84
IFS4=57
REF4=76
IFS5=63
REF5=70


[MultiFP]
MultiThreadImg=1
MultiFP_ImgShow=2
MultiPanelA=
MultiPanelB=
MultiPanelC=
MultiPanelD=
MultiPanelE=
MultiPanelF=
MultiPanelG=
MultiPanelH=
