// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetHVPSDetails() {
  return window['go']['components']['HVPSService']['GetHVPSDetails']();
}

export function HVPSGetSetpointInfo() {
  return window['go']['components']['HVPSService']['HVPSGetSetpointInfo']();
}

export function HVPSSetFilamentLimit(arg1) {
  return window['go']['components']['HVPSService']['HVPSSetFilamentLimit'](arg1);
}

export function HVPSSetFilamentOpen(arg1) {
  return window['go']['components']['HVPSService']['HVPSSetFilamentOpen'](arg1);
}

export function HVPSSetFilamentPreheat(arg1) {
  return window['go']['components']['HVPSService']['HVPSSetFilamentPreheat'](arg1);
}

export function HVPSSetHI(arg1) {
  return window['go']['components']['HVPSService']['HVPSSetHI'](arg1);
}

export function HVPSSetHV(arg1) {
  return window['go']['components']['HVPSService']['HVPSSetHV'](arg1);
}

export function HVPSSetRemote(arg1) {
  return window['go']['components']['HVPSService']['HVPSSetRemote'](arg1);
}

export function HVPSSourceOpen(arg1) {
  return window['go']['components']['HVPSService']['HVPSSourceOpen'](arg1);
}

export function HighVoltageConnect(arg1, arg2) {
  return window['go']['components']['HVPSService']['HighVoltageConnect'](arg1, arg2);
}

export function HighVoltageDisconnect() {
  return window['go']['components']['HVPSService']['HighVoltageDisconnect']();
}

export function HighVoltageIsConnected() {
  return window['go']['components']['HVPSService']['HighVoltageIsConnected']();
}

export function SetContent(arg1) {
  return window['go']['components']['HVPSService']['SetContent'](arg1);
}
