// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {components} from '../models';
import {context} from '../models';

export function GetHVPSDetails():Promise<void>;

export function HVPSGetSetpointInfo():Promise<components.HVPSSetpointInfo>;

export function HVPSSetFilamentLimit(arg1:number):Promise<void>;

export function HVPSSetFilamentOpen(arg1:boolean):Promise<void>;

export function HVPSSetFilamentPreheat(arg1:number):Promise<void>;

export function HVPSSetHI(arg1:number):Promise<void>;

export function HVPSSetHV(arg1:number):Promise<void>;

export function HVPSSetRemote(arg1:boolean):Promise<void>;

export function HVPSSourceOpen(arg1:boolean):Promise<void>;

export function HighVoltageConnect(arg1:string,arg2:number):Promise<void>;

export function HighVoltageDisconnect():Promise<void>;

export function HighVoltageIsConnected():Promise<boolean>;

export function SetContent(arg1:context.Context):Promise<void>;
