// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetStagesDetails() {
  return window['go']['components']['StageService']['GetStagesDetails']();
}

export function SetAxisResolution(arg1, arg2) {
  return window['go']['components']['StageService']['SetAxisResolution'](arg1, arg2);
}

export function SetAxisSpeed(arg1, arg2) {
  return window['go']['components']['StageService']['SetAxisSpeed'](arg1, arg2);
}

export function StagesABSMove(arg1, arg2) {
  return window['go']['components']['StageService']['StagesABSMove'](arg1, arg2);
}

export function StagesConnect(arg1) {
  return window['go']['components']['StageService']['StagesConnect'](arg1);
}

export function StagesDisconnect() {
  return window['go']['components']['StageService']['StagesDisconnect']();
}

export function StagesJOGMove(arg1, arg2) {
  return window['go']['components']['StageService']['StagesJOGMove'](arg1, arg2);
}

export function StagesRELMove(arg1, arg2) {
  return window['go']['components']['StageService']['StagesRELMove'](arg1, arg2);
}

export function StagesSTOPMove(arg1) {
  return window['go']['components']['StageService']['StagesSTOPMove'](arg1);
}

export function Startup(arg1) {
  return window['go']['components']['StageService']['Startup'](arg1);
}
