// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function GetStagesDetails():Promise<void>;

export function SetAxisResolution(arg1:string,arg2:number):Promise<void>;

export function SetAxisSpeed(arg1:string,arg2:number):Promise<void>;

export function StagesABSMove(arg1:string,arg2:number):Promise<void>;

export function StagesConnect(arg1:string):Promise<void>;

export function StagesDisconnect():Promise<void>;

export function StagesJOGMove(arg1:string,arg2:number):Promise<void>;

export function StagesRELMove(arg1:string,arg2:number):Promise<void>;

export function StagesSTOPMove(arg1:string):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;
