// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';

export function APIUpdate():Promise<services.GitHubRelease>;

export function GetCachedRelease():Promise<services.GitHubRelease>;
